In [17]:
import pandas as pd
import numpy as np


dataset=pd.read_csv('house_price.csv') #Bangalore dataset and has 1000 entries
dataset.isnull().values.any()  #to check null values

False

In [18]:
print(dataset) 

     Unnamed: 0      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  \
0            37  Bommanahalli    3           1   3000           1      3   
1            43  Bommanahalli    3           1   1650          10      0   
2            12    Whitefield    2           0   1000           5      3   
3             8    Whitefield    3           0   1600           1      9   
4             9    Whitefield    2           1   1200           5      1   
..          ...           ...  ...         ...    ...         ...    ...   
995          48  Bommanahalli    3           1   1460           1      2   
996           0    Whitefield    3           0   2100           1      7   
997          42  Bommanahalli    2           0   1033           5      0   
998          39  Bommanahalli    3           0   1500          10      1   
999           3    Whitefield    3           1   1768           5     11   

     Price  
0    28000  
1    18000  
2    16400  
3    27000  
4    20000  
..     ..

In [19]:
dataset=dataset.drop(dataset.columns[[0]],axis=1)
print(dataset)                      #locaton has only two fields i.e.,Bommanahalli and whitefield

         Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0    Bommanahalli    3           1   3000           1      3  28000
1    Bommanahalli    3           1   1650          10      0  18000
2      Whitefield    2           0   1000           5      3  16400
3      Whitefield    3           0   1600           1      9  27000
4      Whitefield    2           1   1200           5      1  20000
..            ...  ...         ...    ...         ...    ...    ...
995  Bommanahalli    3           1   1460           1      2  25000
996    Whitefield    3           0   2100           1      7  28000
997  Bommanahalli    2           0   1033           5      0  16500
998  Bommanahalli    3           0   1500          10      1  22000
999    Whitefield    3           1   1768           5     11  30000

[1000 rows x 7 columns]


In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

dataset.Location=le.fit_transform(dataset.Location)
print(dataset)

     Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0           0    3           1   3000           1      3  28000
1           0    3           1   1650          10      0  18000
2           1    2           0   1000           5      3  16400
3           1    3           0   1600           1      9  27000
4           1    2           1   1200           5      1  20000
..        ...  ...         ...    ...         ...    ...    ...
995         0    3           1   1460           1      2  25000
996         1    3           0   2100           1      7  28000
997         0    2           0   1033           5      0  16500
998         0    3           0   1500          10      1  22000
999         1    3           1   1768           5     11  30000

[1000 rows x 7 columns]


In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer([("Location",OneHotEncoder(),[0])],remainder = 'passthrough')
dataset=ct.fit_transform(dataset)
print(dataset)

[[1.00e+00 0.00e+00 3.00e+00 ... 1.00e+00 3.00e+00 2.80e+04]
 [1.00e+00 0.00e+00 3.00e+00 ... 1.00e+01 0.00e+00 1.80e+04]
 [0.00e+00 1.00e+00 2.00e+00 ... 5.00e+00 3.00e+00 1.64e+04]
 ...
 [1.00e+00 0.00e+00 2.00e+00 ... 5.00e+00 0.00e+00 1.65e+04]
 [1.00e+00 0.00e+00 3.00e+00 ... 1.00e+01 1.00e+00 2.20e+04]
 [0.00e+00 1.00e+00 3.00e+00 ... 5.00e+00 1.10e+01 3.00e+04]]


In [22]:
X = dataset[:,1:-1]
y = dataset[:,-1]

# X = dataset.drop(['Price'], axis=1)
# y = dataset['Price']


print(X)
print(y)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression() 
regressor.fit(X, y)
print(regressor.score(X,y))

[[0.000e+00 3.000e+00 1.000e+00 3.000e+03 1.000e+00 3.000e+00]
 [0.000e+00 3.000e+00 1.000e+00 1.650e+03 1.000e+01 0.000e+00]
 [1.000e+00 2.000e+00 0.000e+00 1.000e+03 5.000e+00 3.000e+00]
 ...
 [0.000e+00 2.000e+00 0.000e+00 1.033e+03 5.000e+00 0.000e+00]
 [0.000e+00 3.000e+00 0.000e+00 1.500e+03 1.000e+01 1.000e+00]
 [1.000e+00 3.000e+00 1.000e+00 1.768e+03 5.000e+00 1.100e+01]]
[28000. 18000. 16400. 27000. 20000. 39500. 35000. 42000. 28000. 35000.
 21000. 16400. 14000. 22000. 16000. 14000. 45000. 28000. 23000. 45000.
 39500. 16500. 16000. 21000. 18000. 39000. 26000. 26000. 15500. 20000.
 15500. 20000. 35000. 17000. 15500. 20000. 14000. 35000. 21000. 28000.
 28000. 27000. 24000. 17000. 15500. 16500. 27000. 15500. 14000. 30000.
 16000. 25000. 20000. 30000. 39000. 24000. 20000. 18000. 16400. 19000.
 35000. 22000. 15500. 23000. 42000. 28000. 39000. 14000. 15500. 19500.
 26000. 14000. 19000. 14000. 22000. 35000. 20000. 30000. 22000. 26000.
 22000. 11000. 28000. 26000. 20000. 27000. 20000

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [24]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()  
regressor.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error

y_pred = regressor.predict(X_test)

error = mean_absolute_error(y_test, y_pred)


print("USING MULTI-LINEAR REGRESSION")
print()

print("Testing error - ",end='')
print(error)

y_pred = regressor.predict(X_train)
error = mean_absolute_error(y_train,y_pred)
print("training error - ",end='')
print(error)

USING MULTI-LINEAR REGRESSION

Testing error - 2513.5172646459564
training error - 2452.635887153532


In [25]:
from sklearn.metrics import mean_absolute_error

y_pred = regressor.predict(X_test)
# y_pred=y_pred.reshape(-1,1)
# y_train=y_train.reshape(-1,1)

# print(regressor.score(y_train,y_pred))
error = mean_absolute_error(y_test, y_pred)


print("USING MULTI-LINEAR REGRESSION")
print()

print("Testing error - ",end='')
print(error)

y_pred = regressor.predict(X_train)
error = mean_absolute_error(y_train,y_pred)
print("training error - ",end='')
print(error)

USING MULTI-LINEAR REGRESSION

Testing error - 2513.5172646459564
training error - 2452.635887153532


In [26]:
#example

Ypred=regressor.predict([[0,3,1,3000,1,3]])
                        # [location,no_of_bedrooms,furnishing,sq_foot,old(years),floor]

    
print(Ypred)            # Price 


#example2
Ypred=regressor.predict([[1,2,0,1060,1,1]])
                        # [location,no_of_bedrooms,furnishing,sq_foot,old(years),floor]

    
print(Ypred) 

[36448.47776372]
[18806.24627809]


In [27]:
from sklearn.svm import SVR
model = SVR() 
model.fit(X_train, y_train)


y_pred = model.predict(X_test)
from sklearn.metrics import mean_absolute_error

print("USING SVM ")
print()

print("Testing error - ",end='')
error = mean_absolute_error(y_test, y_pred)

print(error)
y_pred = model.predict(X_train)


error = mean_absolute_error(y_train, y_pred)
print("training error -",end=" ")
print(error)

USING SVM 

Testing error - 6333.62575336172
training error - 5767.727248484664


In [28]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(max_depth = 10, random_state = 14) #hyper-paramenter (tunable) max_leaf_nodes = 20
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
from sklearn.metrics import mean_absolute_error


print("USING DECISION TREE REGRESSOR")
print()

print("OVER FITTING")
print()

error = mean_absolute_error(y_test, y_pred)
print("Testing error")
print(error)
y_pred = model.predict(X_train)


error = mean_absolute_error(y_train, y_pred)
print("training error")
print(error)

USING DECISION TREE REGRESSOR

OVER FITTING

Testing error
0.0
training error
0.0


In [29]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(max_depth = 5, random_state = 14)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
from sklearn.metrics import mean_absolute_error

print("USING RANDOM FOREST REGRESSOR")
print()

error = mean_absolute_error(y_test, y_pred)
print("Testing error")
print(error)

# y_train.reshape(-1,1)
# y_pred.reshape(-1,1)



y_pred = model.predict(X_train)


error = mean_absolute_error(y_train, y_pred)
from sklearn.metrics import accuracy_score


print("training error")
print(error)

USING RANDOM FOREST REGRESSOR

Testing error
645.1948926244279
training error
560.3968410380627


In [30]:
#example1

Ypred=model.predict([[0,3,1,3000,1,3]])
                        # [location,no_of_bedrooms,furnishing,sq_foot,old(years),floor]

    
print(Ypred)            # Price 


#example2
Ypred=model.predict([[1,2,0,1060,1,1]])
                        # [location,no_of_bedrooms,furnishing,sq_foot,old(years),floor]

    
print(Ypred)            # Price 

[28000.]
[17079.05538284]
