In [33]:
import pandas as pd
import numpy as np


dataset=pd.read_csv('cleandataset.csv')

In [34]:
print(dataset)

             Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0        Bommanahalli    3           1   1650          10      0  18000
1          Whitefield    2           0   1000           5      3  16400
2          Whitefield    3           0   1600           1      9  27000
3          Whitefield    2           1   1200           5      1  20000
4          Whitefield    3           1   1760           5      8  39500
...               ...  ...         ...    ...         ...    ...    ...
1994      Indiranagar    3           0   1600           1      2  25000
1995  Electronic city    2           0   1250           5      3  23000
1996      Indiranagar    3           1   1750           1      2  16000
1997  Electronic city    2           0   1150           4      3  17500
1998      Indiranagar    1           1   1250           3      2  16500

[1999 rows x 7 columns]


In [35]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

dataset.Location=le.fit_transform(dataset.Location)
print(dataset)

      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0            0    3           1   1650          10      0  18000
1            4    2           0   1000           5      3  16400
2            4    3           0   1600           1      9  27000
3            4    2           1   1200           5      1  20000
4            4    3           1   1760           5      8  39500
...        ...  ...         ...    ...         ...    ...    ...
1994         3    3           0   1600           1      2  25000
1995         2    2           0   1250           5      3  23000
1996         3    3           1   1750           1      2  16000
1997         2    2           0   1150           4      3  17500
1998         3    1           1   1250           3      2  16500

[1999 rows x 7 columns]


In [36]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer([("Location",OneHotEncoder(),[0])],remainder = 'passthrough')
dataset=ct.fit_transform(dataset)
print(dataset)

[[1.00e+00 0.00e+00 0.00e+00 ... 1.00e+01 0.00e+00 1.80e+04]
 [0.00e+00 0.00e+00 0.00e+00 ... 5.00e+00 3.00e+00 1.64e+04]
 [0.00e+00 0.00e+00 0.00e+00 ... 1.00e+00 9.00e+00 2.70e+04]
 ...
 [0.00e+00 0.00e+00 0.00e+00 ... 1.00e+00 2.00e+00 1.60e+04]
 [0.00e+00 0.00e+00 1.00e+00 ... 4.00e+00 3.00e+00 1.75e+04]
 [0.00e+00 0.00e+00 0.00e+00 ... 3.00e+00 2.00e+00 1.65e+04]]


In [37]:
X = dataset[:,1:-1]
y = dataset[:,-1]

print(X)
print(y)


[[0.00e+00 0.00e+00 0.00e+00 ... 1.65e+03 1.00e+01 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 ... 1.00e+03 5.00e+00 3.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 ... 1.60e+03 1.00e+00 9.00e+00]
 ...
 [0.00e+00 0.00e+00 1.00e+00 ... 1.75e+03 1.00e+00 2.00e+00]
 [0.00e+00 1.00e+00 0.00e+00 ... 1.15e+03 4.00e+00 3.00e+00]
 [0.00e+00 0.00e+00 1.00e+00 ... 1.25e+03 3.00e+00 2.00e+00]]
[18000. 16400. 27000. ... 16000. 17500. 16500.]


In [38]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)


In [39]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(max_depth = 5, random_state = 14)
model.fit(X_train, y_train)


print("RANDOM FOREST REGRESSOR")

print("TRAINING DATA ACCURACY - ",end="")
print(model.score(X_train,y_train))

print("TESTING DATA ACCURACY - ",end="")
print(model.score(X_test,y_test))


RANDOM FOREST REGRESSOR
TRAINING DATA ACCURACY - 0.7558810102563441
TESTING DATA ACCURACY - 0.7113398911588872
